# Параметры моделей


SVC: {
    init_config: {
      
        base_model {
          C: 10.0,
          kernel: poly,
          gamma: scale,
          probability: true,
          class_weight: balanced,
          tol: 0.001,
          random_state: 42,
        },

      calibrator_config: {
        method: isotonic,
        random_state: 42
        }

    },
    
    weight: 1.0,
    calibrator: True,
}

